### ISSUE TITLE
能不能迁移到 UMI DVA TS REACT +ANTD ?

### ISSUE THREAD

**Issue by tianlinzx** [wanghairong-i/dva-ts-react-antd#1]
能不能迁移到 UMI DVA TS REACT +ANTD ?

**Comment by ronffy** [comment]
@tianlinzx  是指云谦的umi吧，大致了解过，还没细看，不过既然是同样的主创，而且文档有介绍如何把两个合到一起使用，想必应该简单，我会抽时间看下的，等我的好消息把 😁

**Comment by ronffy** [comment]
@tianlinzx 
久等了😁，单独起了一个项目，[umi + dva + ts + react + antd-mobile](https://github.com/wanghairong-i/umi-dva-typescript-mock)，在完善中，欢迎fork
