### ISSUE TITLE
请教下如何使项目目录下的webpack.config.js生效

### ISSUE THREAD

**Issue by peakandyuri** [wanghairong-i/dva-ts-react-antd#4]
我使用create-react-app创建了一个react项目，仿照着该项目也在项目根目录下创建了webpack.config.js来重写一些配置，但是运行并没有执行这个配置的JS文件，想知道需要怎么配置一下吗？

**Comment by ronffy** [comment]
@peakandyuri  你问的问题跟本项目无任何关系啊 😓
关于这个问题，
你看下怎样跑起项目来的  - `npm start`, 
那就看下npm start 时执行的shell脚本是什么 - `react-scripts start`
那就去 node_modules 文件夹下的 react-scripts 文件夹下看下执行 `react-scripts`命令时对应的执行文件是哪个 。。。 
依次。。。
你的问题就引刃而解了
